import { Product, Testimonial, PortfolioProject, BlogPost } from '@/types'

// Mock Products
export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Premium Corporate Polo',
    description: 'Comfortable and professional polo shirt perfect for corporate environments',
    price: 45,
    originalPrice: 65,
    category: 'Corporate Wear',
    image: 'https://images.unsplash.com/photo-1596701683639-106e8ac7ffad?w=500&h=500&fit=crop',
    rating: 4.8,
    reviews: 245,
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White', 'Black', 'Gray'],
  },
  {
    id: 2,
    name: 'Medical Scrubs Set',
    description: 'High-quality medical scrubs with superior comfort and durability',
    price: 55,
    originalPrice: 75,
    category: 'Medical',
    image: '/images/products/medical-scrubs.png',
    rating: 4.9,
    reviews: 312,
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['White', 'Navy', 'Ceil Blue', 'Sage'],
  },
  {
    id: 3,
    name: 'Chef Uniform',
    description: 'Professional chef uniform with premium fabric and tailored fit',
    price: 85,
    originalPrice: 120,
    category: 'Hospitality',
    image: '/images/products/chef-uniform.png',
    rating: 4.7,
    reviews: 156,
    inStock: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Gray'],
  },
  {
    id: 4,
    name: 'Safety Vest',
    description: 'High-visibility safety vest with reflective strips',
    price: 35,
    originalPrice: 50,
    category: 'Safety',
    image: '/images/products/safety-vest.png',
    rating: 4.6,
    reviews: 198,
    inStock: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Orange', 'Yellow', 'Green'],
  },
  {
    id: 5,
    name: 'School Blazer',
    description: 'Classic school blazer with durable construction',
    price: 95,
    originalPrice: 135,
    category: 'School Uniforms',
    image: '/images/products/school-blazer.png',
    rating: 4.8,
    reviews: 267,
    inStock: true,
    sizes: ['8', '10', '12', '14', '16', '18'],
    colors: ['Navy', 'Black', 'Burgundy'],
  },
  {
    id: 6,
    name: 'Sports Jersey',
    description: 'Lightweight and breathable sports jersey for active use',
    price: 38,
    originalPrice: 55,
    category: 'Sports Wear',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    rating: 4.7,
    reviews: 189,
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Red', 'Blue', 'White', 'Black'],
  },
  {
    id: 7,
    name: 'Corporate T-Shirt',
    description: 'Versatile t-shirt perfect for branding and corporate gifts',
    price: 28,
    originalPrice: 40,
    category: 'Corporate Wear',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    rating: 4.9,
    reviews: 456,
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Navy', 'White', 'Black', 'Gray', 'Red', 'Blue'],
  },
  {
    id: 8,
    name: 'Nursing Scrubs',
    description: 'Comfortable nursing scrubs with practical pockets',
    price: 60,
    originalPrice: 85,
    category: 'Medical',
    image: '/images/products/nursing-1.jpg',
    rating: 4.8,
    reviews: 234,
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Navy', 'Ceil', 'Lavender'],
  },
  {
    id: 9,
    name: 'Hotel Staff Uniform',
    description: 'Elegant uniform for hospitality and hotel staff',
    price: 75,
    originalPrice: 105,
    category: 'Hospitality',
    image: '/images/products/hotel-1.jpg',
    rating: 4.6,
    reviews: 142,
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Burgundy'],
  },
  {
    id: 10,
    name: 'Industrial Work Shirt',
    description: 'Durable work shirt designed for industrial environments',
    price: 52,
    originalPrice: 75,
    category: 'Industrial',
    image: '/images/products/workshirt-1.jpg',
    rating: 4.7,
    reviews: 203,
    inStock: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Khaki', 'Navy', 'Gray', 'Orange'],
  },
  {
    id: 11,
    name: 'Branded Cap',
    description: 'Premium branded cap perfect for corporate giveaways',
    price: 18,
    originalPrice: 28,
    category: 'Accessories',
    image: '/images/products/cap-1.jpg',
    rating: 4.7,
    reviews: 189,
    inStock: true,
    sizes: ['One Size'],
    colors: ['Navy', 'White', 'Black', 'Red'],
  },
  {
    id: 12,
    name: 'Eco-Friendly Tote Bag',
    description: 'Sustainable tote bag perfect for corporate branding',
    price: 22,
    originalPrice: 35,
    category: 'Accessories',
    image: '/images/products/totebag-1.jpg',
    rating: 4.8,
    reviews: 267,
    inStock: true,
    sizes: ['One Size'],
    colors: ['Natural', 'Navy', 'Black'],
  },
  {
    id: 13,
    name: 'Premium Jacket',
    description: 'Warm and stylish corporate jacket',
    price: 125,
    originalPrice: 180,
    category: 'Corporate Wear',
    image: '/images/products/jacket-1.jpg',
    rating: 4.9,
    reviews: 198,
    inStock: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'Black', 'Gray', 'Charcoal'],
  },
  {
    id: 14,
    name: 'Technical Pants',
    description: 'Comfortable technical pants for all-day wear',
    price: 68,
    originalPrice: 95,
    category: 'Corporate Wear',
    image: '/images/products/pants-1.jpg',
    rating: 4.7,
    reviews: 156,
    inStock: true,
    sizes: ['28', '30', '32', '34', '36', '38', '40'],
    colors: ['Navy', 'Black', 'Khaki', 'Gray'],
  },
  {
    id: 15,
    name: 'School Shirt',
    description: 'Classic school dress shirt with easy care',
    price: 32,
    originalPrice: 48,
    category: 'School Uniforms',
    image: '/images/products/schoolshirt-1.jpg',
    rating: 4.8,
    reviews: 234,
    inStock: true,
    sizes: ['8', '10', '12', '14', '16', '18'],
    colors: ['White', 'Light Blue', 'Pink'],
  },
]

// Mock Testimonials
export const mockTestimonials: Testimonial[] = [
  {
    id: 1,
    name: 'John Anderson',
    company: 'Tech Innovations Inc',
    role: 'HR Director',
    content:
      'JIRE Garments transformed our corporate image. The quality is exceptional and the custom design service was outstanding. Highly recommended!',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    date: '2024-01-15',
  },
  {
    id: 2,
    name: 'Sarah Mitchell',
    company: 'City Hospital',
    role: 'Procurement Manager',
    content:
      'We&apos;ve been ordering medical scrubs from JIRE for over 2 years. Consistent quality, great service, and competitive pricing. Our staff loves them!',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    date: '2024-01-10',
  },
  {
    id: 3,
    name: 'Michael Chen',
    company: 'Premier Hotels Group',
    role: 'Operations Director',
    content:
      'The attention to detail in our custom uniforms is incredible. JIRE understood our brand vision perfectly and delivered beyond expectations.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    date: '2024-01-05',
  },
  {
    id: 4,
    name: 'Emily Roberts',
    company: 'Fashion Forward Retail',
    role: 'Store Manager',
    content:
      'Quick turnaround time, excellent customer service, and the embroidery work is top-notch. Our team looks more professional than ever!',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    date: '2023-12-28',
  },
  {
    id: 5,
    name: 'David Thompson',
    company: 'Industrial Solutions Ltd',
    role: 'Safety Manager',
    content:
      'JIRE provides outstanding safety wear that meets all regulations. Their professionalism and reliability are exactly what we need.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    date: '2023-12-20',
  },
]

// Mock Portfolio Projects
export const mockPortfolioProjects: PortfolioProject[] = [
  {
    id: 1,
    title: 'Tech Corp Rebrand',
    description: 'Complete corporate identity transformation with custom uniforms',
    category: 'Corporate Branding',
    image: '/images/portfolio/techcorp-1.jpg',
    industry: 'Technology',
    brandingType: 'Logo Embroidery',
    uniformType: 'Corporate Polo & T-Shirts',
    results: [
      '500+ uniforms delivered',
      '98% employee satisfaction',
      'Enhanced brand recognition',
    ],
    date: '2024-01-15',
  },
  {
    id: 2,
    title: 'Healthcare Facility Uniforms',
    description: 'Custom medical scrubs for 200+ healthcare professionals',
    category: 'Medical Uniforms',
    image: '/images/portfolio/healthcare-1.jpg',
    industry: 'Healthcare',
    brandingType: 'Embroidered Name Tags',
    uniformType: 'Medical Scrubs',
    results: [
      '1000+ scrubs produced',
      'Improved patient experience',
      'Staff satisfaction: 99%',
    ],
    date: '2024-01-10',
  },
  {
    id: 3,
    title: 'Luxury Hotel Brand Refresh',
    description: 'Premium hospitality uniforms for 5-star hotel chain',
    category: 'Hospitality',
    image: '/images/portfolio/hotel-1.jpg',
    industry: 'Hospitality',
    brandingType: 'Screen Printing',
    uniformType: 'Staff Uniforms',
    results: [
      '300+ uniforms',
      'Elevated brand perception',
      'Guest feedback: Excellent',
    ],
    date: '2024-01-05',
  },
  {
    id: 4,
    title: 'School District Uniforms',
    description: 'Standardized uniforms for 10 schools across the district',
    category: 'Educational Uniforms',
    image: '/images/portfolio/school-1.jpg',
    industry: 'Education',
    brandingType: 'Screen Printing',
    uniformType: 'School Uniforms',
    results: [
      '2000+ uniforms',
      'Improved school identity',
      'Reduced dress code violations',
    ],
    date: '2023-12-28',
  },
  {
    id: 5,
    title: 'Industrial Safety Program',
    description: 'Complete safety wear solution for manufacturing facility',
    category: 'Safety Apparel',
    image: '/images/portfolio/industrial-1.jpg',
    industry: 'Manufacturing',
    brandingType: 'Sublimation',
    uniformType: 'Safety Vests & Work Shirts',
    results: [
      '600+ safety items',
      'Improved safety compliance',
      'Accident reduction: 35%',
    ],
    date: '2023-12-20',
  },
  {
    id: 6,
    title: 'Retail Chain Rollout',
    description: 'Brand-new uniform design for 50-store retail chain',
    category: 'Retail Uniforms',
    image: '/images/portfolio/retail-1.jpg',
    industry: 'Retail',
    brandingType: 'Heat Press',
    uniformType: 'T-Shirts & Vests',
    results: [
      '5000+ uniforms',
      'Consistent brand image',
      'Sales increase: 15%',
    ],
    date: '2023-12-15',
  },
]

// Mock Blog Posts
export const mockBlogPosts: BlogPost[] = [
  {
    id: 1,
    title: 'The Importance of Professional Uniforms in Corporate Culture',
    slug: 'professional-uniforms-corporate-culture',
    excerpt: 'Learn how professional uniforms can strengthen your corporate culture and brand identity.',
    content:
      'Professional uniforms play a crucial role in establishing corporate culture and brand identity. They create a sense of unity among employees and enhance the professional image of your organization. In this article, we explore the multiple benefits of investing in quality corporate uniforms...',
    author: 'James Wilson',
    category: 'Corporate',
    image: '/images/blog/culture-1.jpg',
    publishedAt: '2024-01-15',
    readTime: 5,
    tags: ['Corporate', 'Uniforms', 'Branding'],
  },
  {
    id: 2,
    title: 'Custom Branding: 5 Embroidery Techniques You Should Know',
    slug: 'embroidery-techniques-guide',
    excerpt: 'Discover the top 5 embroidery techniques that can elevate your brand visibility.',
    content:
      'Embroidery is one of the most effective ways to brand corporate uniforms. From simple logo embroidery to complex multi-color designs, there are numerous techniques available. In this comprehensive guide, we explore five techniques that can make your uniforms stand out...',
    author: 'Sarah Design',
    category: 'Design',
    image: '/images/blog/embroidery-1.jpg',
    publishedAt: '2024-01-10',
    readTime: 7,
    tags: ['Branding', 'Embroidery', 'Design'],
  },
  {
    id: 3,
    title: 'Sustainable Uniforms: How to Make Eco-Friendly Choices',
    slug: 'sustainable-uniforms-eco-friendly',
    excerpt: 'Explore sustainable fabric options and eco-friendly uniform manufacturing practices.',
    content:
      'In today&apos;s environmentally conscious world, many organizations are seeking sustainable uniform solutions. From organic cotton to recycled materials, there are several eco-friendly options available. This article discusses how you can make sustainable choices without compromising on quality...',
    author: 'Emma Green',
    category: 'Sustainability',
    image: '/images/blog/sustainable-1.jpg',
    publishedAt: '2024-01-05',
    readTime: 6,
    tags: ['Sustainability', 'Eco-Friendly', 'Corporate'],
  },
  {
    id: 4,
    title: 'Medical Uniform Standards: What Healthcare Facilities Need to Know',
    slug: 'medical-uniform-standards',
    excerpt: 'Understanding compliance requirements and standards for medical uniforms.',
    content:
      'Medical uniforms must meet strict standards for hygiene, comfort, and compliance. Healthcare facilities need to understand these requirements to ensure both patient safety and staff wellbeing. In this guide, we break down the essential medical uniform standards...',
    author: 'Dr. Michael Hart',
    category: 'Healthcare',
    image: '/images/blog/medical-1.jpg',
    publishedAt: '2023-12-28',
    readTime: 8,
    tags: ['Healthcare', 'Medical', 'Standards'],
  },
  {
    id: 5,
    title: 'Uniform Sizing Guide: How to Get the Perfect Fit',
    slug: 'uniform-sizing-guide',
    excerpt: 'Complete guide to measuring and selecting the right uniform sizes for your team.',
    content:
      'Proper sizing is crucial for comfort and professional appearance. Ill-fitting uniforms can negatively impact employee morale and brand image. This comprehensive sizing guide walks you through measuring procedures and size selection tips to ensure your team looks and feels great...',
    author: 'Lisa Fashion',
    category: 'Guide',
    image: '/images/blog/sizing-1.jpg',
    publishedAt: '2023-12-20',
    readTime: 5,
    tags: ['Sizing', 'Guide', 'Uniforms'],
  },
]

// Statistics for Home Page
export const homeStats = [
  { label: 'Projects Completed', value: 1000 },
  { label: 'Happy Clients', value: 500 },
  { label: 'Years in Business', value: 15 },
  { label: 'Satisfaction Rate', value: 98 },
]

// How It Works Steps
export const howItWorksSteps = [
  {
    step: 1,
    title: 'Consultation',
    description: 'Tell us about your requirements and brand vision',
  },
  {
    step: 2,
    title: 'Design',
    description: 'Our designers create custom designs tailored to your needs',
  },
  {
    step: 3,
    title: 'Sampling',
    description: 'Receive samples for approval and quality assurance',
  },
  {
    step: 4,
    title: 'Production',
    description: 'We manufacture your uniforms with premium quality',
  },
  {
    step: 5,
    title: 'Delivery',
    description: 'Fast and reliable shipping to your location',
  },
]

// Navigation for footer and header
export const footerSocialLinks = [
  { label: 'Facebook', href: 'https://facebook.com' },
  { label: 'Twitter', href: 'https://twitter.com' },
  { label: 'Instagram', href: 'https://instagram.com' },
  { label: 'LinkedIn', href: 'https://linkedin.com' },
]
